### PR TITLE
feat: avoid warnings while role-playing in MSQ

### PR DESCRIPTION
**Pull request by deansheather**
Some main story quests let you play as another character with the "Role-playing" status effect. However, the plugin still warns you about missing tank stance or missing food etc. even though you can't cast those actions. During these quests it's necessary to turn off all warnings from the plugin.

Adds a setting to most modules (enabled by default) which disables warnings while you have the "Role-playing" status effect.

I've been unable to test this with the actual RP status effect since I don't know a quick way to get to a quest with said effect, but I've tested it with other status effect IDs and it seems to work.

### CODE REVIEW

**Comment by deansheather** [comment]
I considered making this a list and adding it to the BlacklistController but I couldn't come up with any other status effects that might lead someone to want to disable warnings, so I made it a simple boolean instead. If you can come up with a use case or if you want me to reimplement it that way anyways before merge let me know and I'll give it a shot.

**Comment by MidoriKami** [comment]
Do not make it a toggleable option.

It should just disable everything while roleplaying.

**Comment by deansheather** [comment]
Sure, I can do that

**Comment by deansheather** [comment]
@MidoriKami done, it's always disabled now while role-playing and isn't configurable

**Comment by MidoriKami** [comment]
Sorry for the trouble, I'm going to close this an implement it a bit differently.

**Comment by MidoriKami** [comment]
Implemented in 45e71aa8e43b81114e6b8c559cb47627269da3ab

**Pull request closed without merging**
